os: Visual Studio 2015 RC
version: "{branch}-{build}"

install:
  - ps: (new-object net.webclient).DownloadFile('http://downloads.coapp.org/files/CoApp.Tools.Powershell.msi', 'C:\CoApp.Tools.Powershell.msi')
  - ps: Start-Process -FilePath msiexec -ArgumentList /i, 'C:\CoApp.Tools.Powershell.msi', /quiet -Wait
  - ps: $env:PSModulePath = $env:PSModulePath + ';C:\Program Files (x86)\Outercurve Foundation\Modules'
  - ps: Import-Module CoApp

build_script:
  - ps: .\scripts\nuget_build.bat

test_script:
  - ps: .\tests\autotest-appveyor.ps1

artifacts:
  - path: .\scripts\*.nupkg